# Generated by Django 2.2 on 2020-02-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YouTaxiAdmin', '0006_auto_20200210_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originLatitude', models.TextField()),
                ('originLongitude', models.TextField()),
                ('destinationLatitude', models.TextField()),
                ('destinationLongitude', models.TextField()),
                ('taxiType', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YouTaxiAdmin.Admin')),
            ],
        ),
    ]
