# Generated by Django 2.2 on 2020-02-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YouTaxiAdmin', '0007_userbooking'),
        ('YouTaxiAdmin', '0007_auto_20200212_0734'),
    ]

    operations = [
    ]
