# Generated by Django 2.2 on 2020-02-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YouTaxiUser', '0004_auto_20200210_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='typeOfClient',
            field=models.CharField(choices=[('GOLD', 'GOLD'), ('SILVER', 'SILVER'), ('BRONZE', 'BRONZE'), ('NONE', 'NONE')], default='', max_length=10),
        ),
    ]
